name: End-to-end tests
on: push
jobs:
  chrome-e2e:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/aula04/E2ESwagLabs.cy.js
